import type { Expr, FunctionDecl, Stmt, TypeName } from './ast.js'
import type { CheckedProgram } from './checker.js'
import { builtins } from './builtins.js'

export function emitWgsl(program: CheckedProgram, entry?: string): string {
  const roots = entry ? [requireGpu(program, entry)] : program.functions.filter(fn => fn.target === 'gpu')
  if (roots.length === 0) throw new Error('no gpu functions found')
  const needed = new Set<string>()
  const visit = (fn: FunctionDecl) => {
    if (needed.has(fn.name)) return
    needed.add(fn.name)
    for (const call of callsIn(fn.body)) {
      if (builtins[call]) continue
      const dep = program.functionMap.get(call)
      if (dep && dep.target !== 'cpu') visit(dep)
    }
  }
  roots.forEach(visit)
  const functions = program.functions.filter(fn => needed.has(fn.name))
  return `// Generated by NIH v2 bootstrap compiler.\n// Same source functions are executable by the CPU interpreter and translatable to GPU code.\n\n${functions.map(emitFunction).join('\n\n')}\n`
}

function requireGpu(program: CheckedProgram, name: string): FunctionDecl {
  const fn = program.functionMap.get(name)
  if (!fn) throw new Error(`GPU entry ${name} not found`)
  if (fn.target !== 'gpu') throw new Error(`${name} is ${fn.target}, not gpu`)
  return fn
}

function emitFunction(fn: FunctionDecl): string {
  const params = fn.params.map(p => `${safe(p.name)}: ${wgslType(p.type)}`).join(', ')
  const ret = fn.returnType === 'void' ? '' : ` -> ${wgslType(fn.returnType)}`
  const lines = emitBlock(fn.body, 1, fn.returnType)
  return `fn ${safe(fn.name)}(${params})${ret} {\n${lines.join('\n')}\n}`
}

function emitBlock(stmts: Stmt[], depth: number, returnType: TypeName): string[] {
  const lines: string[] = []
  const pad = '  '.repeat(depth)
  for (let i = 0; i < stmts.length; i++) {
    const stmt = stmts[i]!
    const isLast = i === stmts.length - 1
    if (stmt.kind === 'bind') lines.push(`${pad}${stmt.mutable ? 'var' : 'let'} ${safe(stmt.name)} = ${emitExpr(stmt.value)};`)
    else if (stmt.kind === 'return') lines.push(`${pad}return${stmt.value ? ` ${emitExpr(stmt.value)}` : ''};`)
    else if (stmt.kind === 'expr') {
      if (isLast && returnType !== 'void') lines.push(`${pad}return ${emitExpr(stmt.expr)};`)
      else lines.push(`${pad}${emitExpr(stmt.expr)};`)
    } else if (stmt.kind === 'if') {
      lines.push(`${pad}if (${emitExpr(stmt.condition)}) {`)
      lines.push(...emitBlock(stmt.thenBody, depth + 1, returnType))
      if (stmt.elseBody.length) {
        lines.push(`${pad}} else {`)
        lines.push(...emitBlock(stmt.elseBody, depth + 1, returnType))
      }
      lines.push(`${pad}}`)
    }
  }
  return lines
}

function emitExpr(expr: Expr): string {
  switch (expr.kind) {
    case 'number': return /[.eE]/.test(expr.raw) ? ensureFloat(expr.raw) : expr.raw
    case 'string': throw new Error('strings cannot be emitted to WGSL')
    case 'bool': return String(expr.value)
    case 'name': return safe(expr.name)
    case 'unary': return `(${expr.op}${emitExpr(expr.value)})`
    case 'binary': return `(${emitExpr(expr.left)} ${expr.op} ${emitExpr(expr.right)})`
    case 'swizzle': return `${emitExpr(expr.value)}.${expr.fields}`
    case 'call': {
      const name = expr.callee === 'saturate' ? 'clamp' : expr.callee === 'lerp' ? 'mix' : expr.callee
      if (expr.callee === 'saturate') return `clamp(${emitExpr(expr.args[0]!)}, 0.0, 1.0)`
      if (expr.callee === 'vec2' || expr.callee === 'vec3' || expr.callee === 'vec4') return `${wgslType(expr.callee)}(${expr.args.map(emitExpr).join(', ')})`
      return `${safe(name)}(${expr.args.map(emitExpr).join(', ')})`
    }
  }
}

function callsIn(stmts: Stmt[]): Set<string> {
  const out = new Set<string>()
  const expr = (e: Expr) => {
    if (e.kind === 'call') { out.add(e.callee); e.args.forEach(expr) }
    else if (e.kind === 'binary') { expr(e.left); expr(e.right) }
    else if (e.kind === 'unary' || e.kind === 'swizzle') expr(e.value)
  }
  const stmt = (s: Stmt) => {
    if (s.kind === 'bind') expr(s.value)
    else if (s.kind === 'return' && s.value) expr(s.value)
    else if (s.kind === 'expr') expr(s.expr)
    else if (s.kind === 'if') { expr(s.condition); s.thenBody.forEach(stmt); s.elseBody.forEach(stmt) }
  }
  stmts.forEach(stmt)
  return out
}

function wgslType(type: TypeName | string): string {
  if (type === 'vec2' || type === 'vec3' || type === 'vec4') return `${type}<f32>`
  return type
}
function ensureFloat(raw: string): string { return raw.includes('.') || /[eE]/.test(raw) ? raw : `${raw}.0` }
function safe(name: string): string { return name.replaceAll('-', '_') }
